### ISSUE TITLE
Using IntSliceFlag results in panic

### ISSUE THREAD

**Issue by mrmylanman** [codegangsta/cli#179]
I am very new to Go, but am trying to convert a few scripts we run in our business to Go as a test to see if it is something I can get on board with.

Your cli library is working out pretty well, and I decided to try out the `IntSliceFlag` functionality so that I can pass in a slice of integers. When I do, I get a panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x55e0b]

goroutine 1 [running]:
github.com/codegangsta/cli.(*IntSlice).String(0x0, 0x0, 0x0)
	/Users/mylanc/Go/src/github.com/codegangsta/cli/flag.go:169 +0x11b
flag.(*FlagSet).Var(0xc208044180, 0x53be50, 0x0, 0x31d790, 0xa, 0x373090, 0x3c)
	/usr/local/Cellar/go/1.4.1/libexec/src/flag/flag.go:669 +0x3c
github.com/codegangsta/cli.func·010(0x31d790, 0xa)
	/Users/mylanc/Go/src/github.com/codegangsta/cli/flag.go:209 +0x84
github.com/codegangsta/cli.eachName(0x31d790, 0xa, 0xc20807b618)
	/Users/mylanc/Go/src/github.com/codegangsta/cli/flag.go:54 +0x11e
github.com/codegangsta/cli.IntSliceFlag.Apply(0x31d790, 0xa, 0x0, 0x373090, 0x3c, 0x344470, 0x1a, 0xc208044180)
	/Users/mylanc/Go/src/github.com/codegangsta/cli/flag.go:210 +0x403
github.com/codegangsta/cli.(*IntSliceFlag).Apply(0xc208036340, 0xc208044180)
	<autogenerated>:24 +0xaa
github.com/codegangsta/cli.flagSet(0x322bb0, 0xa, 0xc208044120, 0x4, 0x6, 0xc208044120)
	/Users/mylanc/Go/src/github.com/codegangsta/cli/flag.go:45 +0x133
github.com/codegangsta/cli.Command.Run(0x322bb0, 0xa, 0x0, 0x0, 0x344570, 0x19, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/mylanc/Go/src/github.com/codegangsta/cli/command.go:55 +0x3bf
github.com/codegangsta/cli.(*App).Run(0xc208034340, 0xc20800a000, 0x8, 0x8, 0x0, 0x0)
	/Users/mylanc/Go/src/github.com/codegangsta/cli/app.go:156 +0xcf7
main.main()
	/Users/mylanc/Go/src/eliza.iotrak.net/mylanc/report-router/main.go:88 +0x831

goroutine 2 [runnable]:
runtime.forcegchelper()
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/proc.go:90
runtime.goexit()
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/mgc0.go:82
runtime.goexit()
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/malloc.go:712
runtime.goexit()
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/asm_amd64.s:2232 +0x1
```

I am attempting to run it through a `Command`, of which the code follows:

```go
	app.Commands = []cli.Command{
		{
			Name:   "run-report",
			Usage:  "Run the specified report.",
			Action: reports.RunReport,
			Flags: []cli.Flag{
				cli.StringFlag{
					Name:   "start, s",
					Usage:  "Date to start querying from (YYYY-MM-DD format)",
					EnvVar: "REPORT_ROUTER_START_DATE",
				},
				cli.StringFlag{
					Name:   "stop, S",
					Usage:  "Date to stop querying from (YYYY-MM-DD format)",
					EnvVar: "REPORT_ROUTER_STOP_DATE",
				},
				cli.IntSliceFlag{
					Name:   "facilities, f",
					Usage:  "The IDs of the facilities to query data from. (1,2,3 format)",
					EnvVar: "REPORT_ROUTER_FACILITY_IDS",
				},
			},
		},
	}
```

Without the `IntSliceFlag` the script runs perfectly fine, but when I add it, I get the nil pointer dereference panic. Does anyone else notice this behavior or is it possible that I am doing something wrong?

Note that this error comes up whether I call it as intended:

```
report-router run-report -s 2014-12-01 -S 2014-12-31 -f 11,12,13
```

Or just simply call help:

```
report-router run-report --help
```

As I said, I am still very new to go so it is possible that I am going about this the wrong way.

Thanks for all the help, and the helpful library!

**Comment by mrmylanman** [comment]
I was able to play with it a little more and found that this only occurs if I do not specify a default value. If I do, things work fine.

Not sure if this is the expected behavior or not, but it solves the issue for me.
